variables:
  GIT_STRATEGY: clone

stages:
  - build
  - deploy

before_script:
    - "sudo chown -R gitlab-runner /home/gitlab-runner"
  
build-test:
    script: 
        - "sudo ./scripts/build.sh"
        - "sudo chown -R gitlab-runner ."
    stage: build
    tags:
        - cmk
        - test
    only:
        - master
    artifacts:
        paths:
            - "packages/*.mkp"
        expire_in: 1 week
        name: $CI_PROJECT_NAME
        
deploy-test:
    script: 
        - "sudo ./scripts/install.sh"
        - "sudo chown -R gitlab-runner ."
    dependencies:
        - build-test
    stage: deploy
    environment: test
    tags:
        - cmk
        - test
